language: java
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
addons:
  apt:
    packages:
    - g++-multilib
    - lib32stdc++6
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
install:
- pwd
- git clone --depth=50 --branch=master https://github.com/pjreiniger/maven_repo.git pjreiniger/maven_repo
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:


# Build Library
- cd RobotCode/snobot2018
- ls
- "./gradlew build"
