version: 1.0.{build}
image: Visual Studio 2015

platform:
- x86
- x64

clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    
    git submodule update --init --recursive

build_script:
- cmd: gradlew.bat build jacocoTestReport
    
after_build:
- cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- cmd: pip install codecov
- cmd: cd ../..
- cmd: dir
- cmd: codecov -f "RobotCode/snobot2018/build/reports/jacoco/test/jacocoTestReport.xml"
 
artifacts:
- path: NetworkTableViewer/2018ShuffleboardWidgets/build/libs/*.jar
  name: Shuffleboard
  
- path: NetworkTableViewer/2018SmartDashboardWidgets/build/libs/*.jar
  name: SmartDashboard
  
- path: RobotCode/snobot2018/build/libs/*.jar
  name: Robot
