!!com.snobot.simulator.config.SimulatorConfig
mAccelerometers: []
mAnalogIO: []
mDefaultI2CWrappers:
  0: None
  1: None
mDefaultSpiWrappers:
  0: ADXRS450
  1: Dotstar
  2: Dotstar
  3: Dotstar
  4: Dotstar
mDigitalIO: []
mEncoders:
- mConnectedSpeedControllerHandle: 2
  mHandle: 0
  mName: Elevator
- mConnectedSpeedControllerHandle: 100
  mHandle: 100
  mName: CAN Encoder (0)
- mConnectedSpeedControllerHandle: 102
  mHandle: 102
  mName: CAN Encoder (2)
mGyros:
- mHandle: 100
  mName: SPI ADXRS450
mPwm:
- mHandle: 2
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 20.0
  mName: Elevator
- mHandle: 100
  mMotorModelConfig:
    mGearReduction: 12.0
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: true
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 0.16666666666
    mLoad: 0.6
  mName: Drive Right (A)
- mHandle: 101
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Drive Right (B)
- mHandle: 102
  mMotorModelConfig:
    mGearReduction: 12.0
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 0.16666666666
    mLoad: 0.6
  mName: Drive Left (A)
- mHandle: 103
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Drive Left (B)
mRelays: []
mSimulatorComponents:
- !!com.snobot.simulator.simulator_components.TankDriveGyroSimulator$TankDriveConfig
  mGyroHandle: 100
  mLeftEncoderHandle: 102
  mRightEncoderHandle: 100
  mTurnKp: 33.33
mSolenoids:
- mHandle: 1
  mName: Claw (A)
- mHandle: 2
  mName: Claw (B)
