!!com.snobot.simulator.config.SimulatorConfig
mAccelerometers: []
mAnalogIO: []
mDefaultI2CWrappers:
  0: None
  1: None
mDefaultSpiWrappers:
  0: ADXRS450
  1: null
  2: null
  3: null
  4: null
mDigitalIO:
- mHandle: 6
  mName: Digital Source6
- mHandle: 7
  mName: Digital Source7
- mHandle: 8
  mName: Digital Source8
- mHandle: 9
  mName: Digital Source9
mEncoders:
- mConnectedSpeedControllerHandle: 0
  mHandle: 0
  mName: drive right
- mConnectedSpeedControllerHandle: 1
  mHandle: 1
  mName: drive left
mGyros:
- mHandle: 100
  mName: SPI ADXRS450
mPwm:
- mHandle: 0
  mMotorModelConfig:
    mGearReduction: 12.0
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 1.0
    mLoad: 0.6
  mName: Drive Right
- mHandle: 1
  mMotorModelConfig:
    mGearReduction: 12.0
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: true
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 1.0
    mLoad: 0.6
  mName: Drive Left
mRelays: []
mSimulatorComponents:
- !!com.snobot.simulator.simulator_components.TankDriveGyroSimulator$TankDriveConfig
  mGyroHandle: 100
  mLeftEncoderHandle: 1
  mRightEncoderHandle: 0
  mTurnKp: 33.33
mSolenoids: []
